/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

/**
 *
 * @author LENOVO
 */
public class HOME extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    public HOME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPERSEGI = new javax.swing.JButton();
        jPERSEGIPANJANG = new javax.swing.JButton();
        jLINGKARAN = new javax.swing.JButton();
        jSEGITIGA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("APLIKASI BANGUN DATAR");

        jPERSEGI.setText("PERSEGI");
        jPERSEGI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPERSEGIActionPerformed(evt);
            }
        });

        jPERSEGIPANJANG.setText("PERSEGI PANJANG");
        jPERSEGIPANJANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPERSEGIPANJANGActionPerformed(evt);
            }
        });

        jLINGKARAN.setText("LINGKARAN ");
        jLINGKARAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLINGKARANActionPerformed(evt);
            }
        });

        jSEGITIGA.setText("SEGITIGA");
        jSEGITIGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSEGITIGAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLINGKARAN)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jSEGITIGA)))
                                .addGap(18, 18, 18))
                            .addComponent(jPERSEGIPANJANG)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jPERSEGI)))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPERSEGI)
                .addGap(18, 18, 18)
                .addComponent(jPERSEGIPANJANG)
                .addGap(18, 18, 18)
                .addComponent(jLINGKARAN)
                .addGap(18, 18, 18)
                .addComponent(jSEGITIGA)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSEGITIGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSEGITIGAActionPerformed
        new SEGITIGA ().setVisible(true);
    }//GEN-LAST:event_jSEGITIGAActionPerformed

    private void jLINGKARANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLINGKARANActionPerformed
       new LINGKARAN ().setVisible(true);
    }//GEN-LAST:event_jLINGKARANActionPerformed

    private void jPERSEGIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPERSEGIActionPerformed
       new PERSEGI() .setVisible(true);
    }//GEN-LAST:event_jPERSEGIActionPerformed

    private void jPERSEGIPANJANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPERSEGIPANJANGActionPerformed
       new PERSEGIPANJANG ().setVisible(true);
    }//GEN-LAST:event_jPERSEGIPANJANGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jLINGKARAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jPERSEGI;
    private javax.swing.JButton jPERSEGIPANJANG;
    private javax.swing.JButton jSEGITIGA;
    // End of variables declaration//GEN-END:variables
}
